import { Overpass } from 'next/font/google';
import { ReactNode } from 'react';
import './globals.css';

const overpass = Overpass({ subsets: ['latin'] });

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default async function RootLayout({ children }: { children: ReactNode }) {
	return (
		<html lang="en">
			<body className={overpass.className}>
				{children}
			</body>
		</html>
	);
}
